version: "3"
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro # bind mount
      - /app/node_modules # anonymous volume
    environment:
      - NODE_ENV=development
      - MONGO_USER=subhra
      - MONGO_PASSWORD=mypass
      - SESSION_SECRET=secrets
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=subhra
      - MONGO_INITDB_ROOT_PASSWORD=mypass
