version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app
  node-app:
    build: .
    image: pseudorandomguy/node-app
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    # no build needed as we are using the original mongo image without making any changes into it
    environment:
      - MONGO_INITDB_ROOT_USERNAME=subhra
      - MONGO_INITDB_ROOT_PASSWORD=mypass
    volumes:
      - mongo-db:/data/db #named volume

  redis:
    image: redis

volumes:
  mongo-db:
